name: Test

on: [push, pull_request]

jobs:
    ubuntu22:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - run: |
                ./test_changes

